config/routes.rb
Rails.application.routes.draw do
  resources :cities, shallow: true do
    resources :houses do
      resources :energies, controller: :house_energies, only: :index
    end
    resources :energies, controller: :city_energies, only: :index
  end
  resources :houses
  resources :energies

  root 'cities#index'
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = params[:city_id] ? House.where(city_id: params[:city_id]) : House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:city_id, :first_name, :last_name, :num_of_people, :has_child)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :num_of_people %>
    <%= form.number_field :num_of_people %>
  </div>

  <div class="field">
    <%= form.label :has_child %>
    <%= form.check_box :has_child %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Num of people</th>
      <th>Has child</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= link_to house.city, house.city %></td>
        <td><%= house.first_name %></td>
        <td><%= house.last_name %></td>
        <td><%= house.num_of_people %></td>
        <td><%= house.has_child %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Energies', house_energies_path(house) %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= link_to @house.city.name, @house.city %>
</p>

<p>
  <strong>First name:</strong>
  <%= @house.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @house.last_name %>
</p>

<p>
  <strong>Num of people:</strong>
  <%= @house.num_of_people %>
</p>

<p>
  <strong>Has child:</strong>
  <%= @house.has_child %>
</p>

<%= link_to 'Energies', house_energies_path(@house) %> |
<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>