config/routes.rb
Rails.application.routes.draw do
  resources :cities, shallow: true do
    resources :houses do
      resources :energies, controller: :house_energies, only: :index
    end
    resources :energies, controller: :city_energies, only: :index
  end
  resources :houses
  resources :energies

  root 'cities#index'
end

app/models/energy.rb
require 'csv'

class Energy < ApplicationRecord
  belongs_to :house
  has_one :city, through: :house

  module CityMethods
    def per_house_hash
      data = {}
      all.includes(:house).group('houses.first_name', :label).each{ |e|
        data[e.house.name] ||= []
        data[e.house.name] << e.energy_production
      }
      data
    end
    def per_has_child_hash
      data = {}
      all.includes(:house).group('houses.has_child', :label).each{ |e|
        p e.house.has_child
        data[e.house.has_child] ||= []
        data[e.house.has_child] << e.energy_production
      }
      data
    end
    [:num_of_people].each{|col|
      define_method "per_#{col}_hash", ->{
        data = {}
        all.includes(:house).group("houses.#{col}", :label).each{ |e|
          data[e.house.send(col)] ||= []
          data[e.house.send(col)] << e.energy_production
        }
        data
      }
    }
  end

  def year_month; "#{year}/#{month}" end
  def self.year_momths
    all.map &:year_month
  end

  def self.avg_per_city_hash
    all.joins(house: :city).group('houses.city_id').pluck('cities.name', 'AVG(energy_production)').to_h
  end

  def self.import_csv path='./data/dataset_50.csv', headers:true, col_sep:','
    data = []
    CSV.foreach(path, headers: headers, col_sep: col_sep) do |row|
      house = House.find row.field('House')
      create!(
        house: house,
        label: row.field('Label'),
        year: row.field('Year'),
        month: row.field('Month'),
        temperature: row.field('Temperature'),
        daylight: row.field('Daylight'),
        energy_production: row.field('EnergyProduction'),
      )
    end
  end
end

app/controllers/energies_controller.rb
class EnergiesController < ApplicationController
  before_action :set_energy, only: [:show, :edit, :update, :destroy]

  # GET /energies
  # GET /energies.json
  def index
    @energies = Energy.all.includes(:house)
    @avg_per_city_hash = @energies.avg_per_city_hash
    gon.data = {
      labels: @energies.year_momths,
      average: {
        temperatures: @energies.pluck(:temperature),
        daylights: @energies.pluck(:daylight),
        energy_productions: @energies.pluck(:energy_production),
      },
      avg_per_city: {
        labels: @avg_per_city_hash.keys,
        data: @avg_per_city_hash.values,
      }
    }
  end

  # GET /energies/1
  # GET /energies/1.json
  def show
  end

  # GET /energies/new
  def new
    @energy = Energy.new
  end

  # GET /energies/1/edit
  def edit
  end

  # POST /energies
  # POST /energies.json
  def create
    @energy = Energy.new(energy_params)

    respond_to do |format|
      if @energy.save
        format.html { redirect_to @energy, notice: 'Energy was successfully created.' }
        format.json { render :show, status: :created, location: @energy }
      else
        format.html { render :new }
        format.json { render json: @energy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /energies/1
  # PATCH/PUT /energies/1.json
  def update
    respond_to do |format|
      if @energy.update(energy_params)
        format.html { redirect_to @energy, notice: 'Energy was successfully updated.' }
        format.json { render :show, status: :ok, location: @energy }
      else
        format.html { render :edit }
        format.json { render json: @energy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /energies/1
  # DELETE /energies/1.json
  def destroy
    @energy.destroy
    respond_to do |format|
      format.html { redirect_to energies_url, notice: 'Energy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_energy
      @energy = Energy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def energy_params
      params.require(:energy).permit(:house_id, :label, :year, :month, :temperature, :daylight, :energy_production)
    end
end

app/helpers/energies_helper.rb
module EnergiesHelper
end

app/views/energies/_form.html.erb
<%= form_with(model: energy, local: true) do |form| %>
  <% if energy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(energy.errors.count, "error") %> prohibited this energy from being saved:</h2>

      <ul>
      <% energy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :house_id %>
    <%= form.text_field :house_id %>
  </div>

  <div class="field">
    <%= form.label :label %>
    <%= form.number_field :label %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.number_field :month %>
  </div>

  <div class="field">
    <%= form.label :temperature %>
    <%= form.text_field :temperature %>
  </div>

  <div class="field">
    <%= form.label :daylight %>
    <%= form.text_field :daylight %>
  </div>

  <div class="field">
    <%= form.label :energy_production %>
    <%= form.number_field :energy_production %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/energies/edit.html.erb
<h1>Editing Energy</h1>

<%= render 'form', energy: @energy %>

<%= link_to 'Show', @energy %> |
<%= link_to 'Back', energies_path %>

app/views/energies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Energies</h1>

<!-- <canvas id="myChart" width="400" height="100"></canvas> -->
<canvas id="avgPerCity" width="400" height="100"></canvas>
<script>
// housesごとに出してるのの平均版を出したかったが時間がないので諦め
// var ctx = document.getElementById('myChart').getContext('2d');
// new Chart(ctx, {
//     type: 'bar',
//     data: {
//       labels: gon.data['labels'],
//       datasets: [
//         {
//           type: 'bar',
//           label: "Daylight",
//           backgroundColor: 'rgba(0, 0, 255, 0.1)',
//           data: gon.data['daylights'],
//           yAxisID: "y-axis-daylight",
//         },
//         {
//           type: 'bar',
//           label: "Temperature",
//           backgroundColor: 'rgb(0, 255, 0, 0.1)',
//           data: gon.data['temperatures'],
//           yAxisID: "y-axis-temperature",
//         },
//         {
//           type: 'line',
//           label: "EnergyProduction",
//           borderColor: 'rgb(255, 99, 132)',
//           fill: false,
//           data: gon.data['energy_productions'],
//           yAxisID: "y-axis-energy_production",
//         },
//       ]
//     },
//     options: {
//       responsive: true,
//       scales: {
//         yAxes: [
//           {
//             id: "y-axis-temperature",
//             type: "linear",
//             position: "left",
//             ticks: {
//               max: 30,
//               min: 0,
//               stepSize: 5
//             },
//           }, {
//             id: "y-axis-energy_production",
//             type: "linear",
//             position: "right",
//             ticks: {
//               max: 1100,
//               min: 200,
//               stepSize: 100
//             },
//           }, {
//             id: "y-axis-daylight",
//             type: "linear",
//             position: "left",
//             ticks: {
//               max: 300,
//               min: 100,
//               stepSize: 50
//             },
//           }
//         ],
//       }
//     }
// });

var ctx = document.getElementById('avgPerCity').getContext('2d');
new Chart(ctx, {
    type: 'pie',
    data: {
      labels: gon.data.avg_per_city.labels,
      datasets: [{
        backgroundColor: ['rgb(' + ColorPallete.getRgb() + ')', 'rgb(' + ColorPallete.getRgb() + ')', 'rgb(' + ColorPallete.getRgb() + ')'],
        data: gon.data.avg_per_city.data,
      }]
    },
    options: {}
});
</script>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Year</th>
      <th>Month</th>
      <th>Temperature</th>
      <th>Daylight</th>
      <th>Energy production</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @energies.each do |energy| %>
      <tr>
        <td><%= energy.label %></td>
        <td><%= energy.year %></td>
        <td><%= energy.month %></td>
        <td><%= energy.temperature %></td>
        <td><%= energy.daylight %></td>
        <td><%= energy.energy_production %></td>
        <td><%= link_to 'Show', energy %></td>
        <td><%= link_to 'Edit', edit_energy_path(energy) %></td>
        <td><%= link_to 'Destroy', energy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Energy', new_energy_path %>

app/views/energies/new.html.erb
<h1>New Energy</h1>

<%= render 'form', energy: @energy %>

<%= link_to 'Back', energies_path %>

app/views/energies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>House:</strong>
  <%= @energy.house %>
</p>

<p>
  <strong>Label:</strong>
  <%= @energy.label %>
</p>

<p>
  <strong>Year:</strong>
  <%= @energy.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @energy.month %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @energy.temperature %>
</p>

<p>
  <strong>Daylight:</strong>
  <%= @energy.daylight %>
</p>

<p>
  <strong>Energy production:</strong>
  <%= @energy.energy_production %>
</p>

<%= link_to 'Edit', edit_energy_path(@energy) %> |
<%= link_to 'Back', energies_path %>